### ISSUE TITLE
Versioning conflicts

### ISSUE THREAD

**Issue by Mtze** [mimacom/ansible-role-bamboo-agent#5]
Good evening!

I tried to install your tool, but ansible-galaxy threw the following error:

` [WARNING]: - mimacom.bamboo-agent was NOT installed successfully: Unable to compare role versions (v0.0.1, 0.0.1) to determine the most recent version due to incompatible version
formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.`

Maybe you can fix the version tag conflict :) 

---
ansible-galaxy 2.5.2
---

Best regards,
Mtze

**Comment by stromvirvel** [comment]
Hi mtze. Thank you, it's resolved now.
