### ISSUE TITLE
bambooagent group is not created

### ISSUE THREAD

**Issue by dblencowe** [mimacom/ansible-role-bamboo-agent#6]
It looks like the role doesn't try to create the bambooagent group before creating the user, resulting in the following error:

`TASK [mimacom.bamboo-agent : Add service user] ***************************************************************************************************************************************
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Group bambooagent does not exist"}`

Happy to create a PR once this is confirmed as an issue.

**Comment by stromvirvel** [comment]
Actually the task creates a group by default, see:
https://docs.ansible.com/ansible/latest/modules/user_module.html

What ansible version and Linux distribution do you use?
